### ISSUE TITLE
superfences detected by markmap note when rendering mkdocs site

### ISSUE THREAD

**Issue by ashugaur** [markmap/mkdocs-markmap#46]
The plugin works well, thank you for building it.

I notice that we get the 'superfences detected by markmap' note when rendering mkdocs site (`mkdocs build`). This list (as in screenshot) increases with the number of pages in the site, consuming time as well as creating doubt of a conflict with superfences.

Any way to fix it?

![Screenshot 2023-05-11 105333](https://github.com/markmap/mkdocs-markmap/assets/19241362/786b1d0e-79a5-4412-a6b8-02825b31a9f0)

**Comment by neatc0der** [comment]
Was fixed with `v2.4.1`, please verify.
