### ISSUE TITLE
Relax attrs version

### ISSUE THREAD

**Issue by tjader** [markmap/mkdocs-markmap#47]
Hi, would it be possible to relax the attrs version required and allow newer versions? 
It is currently locked to attrs==20.3.0, but from what I can see in the code, the attrs use is fairly limited.

**Comment by andynameistaken** [comment]
It blocks upgrading `mkdocs-jupyter`:
```
mkdocs-markmap 2.4.0 requires attrs==20.3.0, but you have attrs 23.1.0 which is incompatible.
```

**Comment by andynameistaken** [comment]
Is it possible to at least update `attrs` to the last version or this project specifically needs `20.3.0`?

**Comment by neatc0der** [comment]
Update in #55: `attrs>=20.3.0`
