### ISSUE TITLE
How to turn off INFO debug information

### ISSUE THREAD

**Issue by SPyofgame** [markmap/mkdocs-markmap#60]
![image](https://github.com/markmap/mkdocs-markmap/assets/62207095/139c0841-0e72-4272-97e4-b6fe79e4ccd2)
![image](https://github.com/markmap/mkdocs-markmap/assets/62207095/2fd954e8-aa93-4203-9bb2-4c16d57e217e)

how can I turn off these

**Comment by neatc0der** [comment]
This kind of logging bothered me, too. Thus, it was fixed in `2.4.3`, see [817efa50](https://github.com/markmap/mkdocs-markmap/commit/817efa506d77b9cb6338787bc473ffbfd4a21f2c).

Please update, then the issue is resolved.
